name: Deploy to EC2

on:
  push:
    branches:
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 1. Use the correct path found by your 'ls' command
            cd /home/ubuntu/resq-disaster-platform
            git pull origin aws

            # 2. Prevent memory crashes during build (important for t3.micro)
            export NODE_OPTIONS="--max-old-space-size=2048"

            export $(grep -v '^#' apps/web/.env.local | xargs)

            # 3. Install and Build
            npm install
            npm run build

            # 4. Sync Database
            npx prisma migrate deploy --schema=packages/database/prisma/schema.prisma

            # 5. Restart with the correct paths
            pm2 restart resq-api --update-env || pm2 start apps/api/dist/main.js --name resq-api
            pm2 restart resq-web --update-env || pm2 start "npm run start --workspace=apps/web" --name resq-web
